/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iotbroker;

import iotpackage.IoTAction;
import iotpackage.Message;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author davi
 */
public class DeviceTester extends javax.swing.JFrame {

    /**
     * Creates new form DeviceTester
     */
    Socket tvSocket;
    ObjectInputStream inFromDevice;
    ObjectOutputStream outToDevice;
    public DeviceTester() {
        
        try {
            initComponents();
            tvSocket = new Socket("localhost", 9092);
            
            
            
            outToDevice = new ObjectOutputStream(tvSocket.getOutputStream());
            outToDevice.flush();
            inFromDevice = new ObjectInputStream(tvSocket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnChangeChannel = new javax.swing.JButton();
        btnChangeVolume = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Toggle Light");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnChangeChannel.setText("Random Channel");
        btnChangeChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeChannelActionPerformed(evt);
            }
        });

        btnChangeVolume.setText("Random Volume");
        btnChangeVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeVolumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangeVolume)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(154, 154, 154))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnChangeChannel)
                            .addGap(137, 137, 137)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(51, 51, 51)
                .addComponent(btnChangeChannel)
                .addGap(26, 26, 26)
                .addComponent(btnChangeVolume)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Message m = new Message("Generic","Message");
        try {
            IoTAction action = new IoTAction(IoTAction.TOGGLE);
            outToDevice.writeObject(action);
            
            m = (Message)inFromDevice.readObject();
            
        } catch (IOException ex) {
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(m.getMessage());
        try {
            outToDevice.flush();
        } catch (IOException ex) {
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            tvSocket.close();
        } catch (IOException ex) {
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnChangeVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeVolumeActionPerformed
        int newVolume = new Random().nextInt();
        Message m = new Message("Generic", "Message");
        try{
            IoTAction action = new IoTAction(IoTAction.SET_VOLUME, newVolume);
            outToDevice.writeObject(action);
            m = (Message)inFromDevice.readObject();
            outToDevice.flush();
            
            
        }catch (IOException | ClassNotFoundException e){
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, e);
        }
        System.out.println(m.getMessage());
    }//GEN-LAST:event_btnChangeVolumeActionPerformed

    private void btnChangeChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeChannelActionPerformed
        int newChannel = new Random().nextInt();
        Message m = new Message("Generic", "Message");
        try{
            IoTAction action = new IoTAction(IoTAction.SET_CHANNEL, newChannel);
            outToDevice.writeObject(action);
            m = (Message)inFromDevice.readObject();
            outToDevice.flush();
            
            
        }catch (IOException | ClassNotFoundException e){
            Logger.getLogger(DeviceTester.class.getName()).log(Level.SEVERE, null, e);
        }
        System.out.println(m.getMessage());
        
    }//GEN-LAST:event_btnChangeChannelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeChannel;
    private javax.swing.JButton btnChangeVolume;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
